name: local
variables:
  - name: base_url
    value: http://localhost:50051
  - name: node_1
    value: localhost:50051
  - name: node_2
    value: localhost:50052
  - name: node_3
    value: localhost:50053
