// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: debug.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{0}
}

type InspectResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	NodeId     []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`             // 16 raw UUID bytes (= CRDT ActorID)
	Generation uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`                  // node start time (ms); orders restarts
	Partitions uint32                 `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`                  // cluster-wide P
	ClientAddr string                 `protobuf:"bytes,4,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"` // client-facing gRPC listen address
	NodeAddr   string                 `protobuf:"bytes,5,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`       // advertised node-facing gRPC address peers dial
	// Membership as THIS node sees it (alive set including self, plus
	// dead-within-grace phantoms).
	Members []*Member `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	// The computed owners table, one entry per partition. Two nodes share an
	// edge in the graph when both appear in the same partition's owners.
	PartitionsTable []*PartitionOwners `protobuf:"bytes,7,rep,name=partitions_table,json=partitionsTable,proto3" json:"partitions_table,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{1}
}

func (x *InspectResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *InspectResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *InspectResponse) GetPartitions() uint32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *InspectResponse) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

func (x *InspectResponse) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

func (x *InspectResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *InspectResponse) GetPartitionsTable() []*PartitionOwners {
	if x != nil {
		return x.PartitionsTable
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`  // node-facing gRPC address
	Dead          bool                   `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"` // dead-within-grace phantom
	Generation    uint64                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Member) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Member) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *Member) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type PartitionOwners struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Owners        []*Owner               `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"` // HRW rank order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionOwners) Reset() {
	*x = PartitionOwners{}
	mi := &file_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionOwners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionOwners) ProtoMessage() {}

func (x *PartitionOwners) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionOwners.ProtoReflect.Descriptor instead.
func (*PartitionOwners) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{3}
}

func (x *PartitionOwners) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionOwners) GetOwners() []*Owner {
	if x != nil {
		return x.Owners
	}
	return nil
}

type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0 none, 1 bootstrapping, 2 active, 3 draining
	Dead          bool                   `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{4}
}

func (x *Owner) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Owner) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Owner) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

type DumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpRequest) Reset() {
	*x = DumpRequest{}
	mi := &file_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpRequest) ProtoMessage() {}

func (x *DumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpRequest.ProtoReflect.Descriptor instead.
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{5}
}

type DebugDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Document      []byte                 `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`                          // rendered JSON; empty when tombstone
	ContextHash   []byte                 `protobuf:"bytes,4,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"` // hash of the causal context (diagnostics)
	Tombstone     bool                   `protobuf:"varint,5,opt,name=tombstone,proto3" json:"tombstone,omitempty"`                       // deleted residual: empty fields, non-empty context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugDoc) Reset() {
	*x = DebugDoc{}
	mi := &file_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugDoc) ProtoMessage() {}

func (x *DebugDoc) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugDoc.ProtoReflect.Descriptor instead.
func (*DebugDoc) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{6}
}

func (x *DebugDoc) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *DebugDoc) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DebugDoc) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *DebugDoc) GetContextHash() []byte {
	if x != nil {
		return x.ContextHash
	}
	return nil
}

func (x *DebugDoc) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

var File_debug_proto protoreflect.FileDescriptor

const file_debug_proto_rawDesc = "" +
	"\n" +
	"\vdebug.proto\x12\n" +
	"convergekv\"\x10\n" +
	"\x0eInspectRequest\"\x9e\x02\n" +
	"\x0fInspectResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x01(\rR\n" +
	"partitions\x12\x1f\n" +
	"\vclient_addr\x18\x04 \x01(\tR\n" +
	"clientAddr\x12\x1b\n" +
	"\tnode_addr\x18\x05 \x01(\tR\bnodeAddr\x12,\n" +
	"\amembers\x18\x06 \x03(\v2\x12.convergekv.MemberR\amembers\x12F\n" +
	"\x10partitions_table\x18\a \x03(\v2\x1b.convergekv.PartitionOwnersR\x0fpartitionsTable\"`\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04dead\x18\x03 \x01(\bR\x04dead\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation\"Z\n" +
	"\x0fPartitionOwners\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12)\n" +
	"\x06owners\x18\x02 \x03(\v2\x11.convergekv.OwnerR\x06owners\"C\n" +
	"\x05Owner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x12\n" +
	"\x04dead\x18\x03 \x01(\bR\x04dead\"\r\n" +
	"\vDumpRequest\"\x97\x01\n" +
	"\bDebugDoc\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1a\n" +
	"\bdocument\x18\x03 \x01(\fR\bdocument\x12!\n" +
	"\fcontext_hash\x18\x04 \x01(\fR\vcontextHash\x12\x1c\n" +
	"\ttombstone\x18\x05 \x01(\bR\ttombstone2\x8d\x01\n" +
	"\x05Debug\x12B\n" +
	"\aInspect\x12\x1a.convergekv.InspectRequest\x1a\x1b.convergekv.InspectResponse\x12@\n" +
	"\rDumpDocuments\x12\x17.convergekv.DumpRequest\x1a\x14.convergekv.DebugDoc0\x01B0Z.github.com/janthoXO/convergeKV/pkg/proto;protob\x06proto3"

var (
	file_debug_proto_rawDescOnce sync.Once
	file_debug_proto_rawDescData []byte
)

func file_debug_proto_rawDescGZIP() []byte {
	file_debug_proto_rawDescOnce.Do(func() {
		file_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debug_proto_rawDesc), len(file_debug_proto_rawDesc)))
	})
	return file_debug_proto_rawDescData
}

var file_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_debug_proto_goTypes = []any{
	(*InspectRequest)(nil),  // 0: convergekv.InspectRequest
	(*InspectResponse)(nil), // 1: convergekv.InspectResponse
	(*Member)(nil),          // 2: convergekv.Member
	(*PartitionOwners)(nil), // 3: convergekv.PartitionOwners
	(*Owner)(nil),           // 4: convergekv.Owner
	(*DumpRequest)(nil),     // 5: convergekv.DumpRequest
	(*DebugDoc)(nil),        // 6: convergekv.DebugDoc
}
var file_debug_proto_depIdxs = []int32{
	2, // 0: convergekv.InspectResponse.members:type_name -> convergekv.Member
	3, // 1: convergekv.InspectResponse.partitions_table:type_name -> convergekv.PartitionOwners
	4, // 2: convergekv.PartitionOwners.owners:type_name -> convergekv.Owner
	0, // 3: convergekv.Debug.Inspect:input_type -> convergekv.InspectRequest
	5, // 4: convergekv.Debug.DumpDocuments:input_type -> convergekv.DumpRequest
	1, // 5: convergekv.Debug.Inspect:output_type -> convergekv.InspectResponse
	6, // 6: convergekv.Debug.DumpDocuments:output_type -> convergekv.DebugDoc
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_debug_proto_init() }
func file_debug_proto_init() {
	if File_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debug_proto_rawDesc), len(file_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_debug_proto_goTypes,
		DependencyIndexes: file_debug_proto_depIdxs,
		MessageInfos:      file_debug_proto_msgTypes,
	}.Build()
	File_debug_proto = out.File
	file_debug_proto_goTypes = nil
	file_debug_proto_depIdxs = nil
}
