// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: debug.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Debug_Inspect_FullMethodName       = "/convergekv.Debug/Inspect"
	Debug_DumpDocuments_FullMethodName = "/convergekv.Debug/DumpDocuments"
)

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Debug is an introspection service for tooling (the debug client). It is
// not part of the production data path: Inspect exposes a node's identity and
// its local placement view, DumpDocuments streams every document the node
// physically holds, rendered to JSON. Both are read-only.
type DebugClient interface {
	// Inspect returns this node's identity plus the membership and owners table
	// as it currently sees them. Views diverge across nodes during churn or a
	// network partition, so callers should inspect every node and compare.
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	// DumpDocuments streams every document this node holds (across all
	// partitions), each rendered to JSON, with tombstones flagged.
	DumpDocuments(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DebugDoc], error)
}

type debugClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugClient(cc grpc.ClientConnInterface) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, Debug_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) DumpDocuments(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DebugDoc], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Debug_ServiceDesc.Streams[0], Debug_DumpDocuments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DumpRequest, DebugDoc]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Debug_DumpDocumentsClient = grpc.ServerStreamingClient[DebugDoc]

// DebugServer is the server API for Debug service.
// All implementations must embed UnimplementedDebugServer
// for forward compatibility.
//
// Debug is an introspection service for tooling (the debug client). It is
// not part of the production data path: Inspect exposes a node's identity and
// its local placement view, DumpDocuments streams every document the node
// physically holds, rendered to JSON. Both are read-only.
type DebugServer interface {
	// Inspect returns this node's identity plus the membership and owners table
	// as it currently sees them. Views diverge across nodes during churn or a
	// network partition, so callers should inspect every node and compare.
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
	// DumpDocuments streams every document this node holds (across all
	// partitions), each rendered to JSON, with tombstones flagged.
	DumpDocuments(*DumpRequest, grpc.ServerStreamingServer[DebugDoc]) error
	mustEmbedUnimplementedDebugServer()
}

// UnimplementedDebugServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDebugServer struct{}

func (UnimplementedDebugServer) Inspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedDebugServer) DumpDocuments(*DumpRequest, grpc.ServerStreamingServer[DebugDoc]) error {
	return status.Error(codes.Unimplemented, "method DumpDocuments not implemented")
}
func (UnimplementedDebugServer) mustEmbedUnimplementedDebugServer() {}
func (UnimplementedDebugServer) testEmbeddedByValue()               {}

// UnsafeDebugServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DebugServer will
// result in compilation errors.
type UnsafeDebugServer interface {
	mustEmbedUnimplementedDebugServer()
}

func RegisterDebugServer(s grpc.ServiceRegistrar, srv DebugServer) {
	// If the following call panics, it indicates UnimplementedDebugServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Debug_ServiceDesc, srv)
}

func _Debug_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Debug_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_DumpDocuments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DebugServer).DumpDocuments(m, &grpc.GenericServerStream[DumpRequest, DebugDoc]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Debug_DumpDocumentsServer = grpc.ServerStreamingServer[DebugDoc]

// Debug_ServiceDesc is the grpc.ServiceDesc for Debug service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Debug_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "convergekv.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inspect",
			Handler:    _Debug_Inspect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DumpDocuments",
			Handler:       _Debug_DumpDocuments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "debug.proto",
}
