// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Forward_FullMethodName      = "/convergekv.Node/Forward"
	Node_ApplyDelta_FullMethodName   = "/convergekv.Node/ApplyDelta"
	Node_MerkleRoot_FullMethodName   = "/convergekv.Node/MerkleRoot"
	Node_MerkleLeaves_FullMethodName = "/convergekv.Node/MerkleLeaves"
	Node_SyncBucket_FullMethodName   = "/convergekv.Node/SyncBucket"
	Node_Snapshot_FullMethodName     = "/convergekv.Node/Snapshot"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Node is the node-facing service: request forwarding, delta replication,
// anti-entropy, and partition transfer streams.
type NodeClient interface {
	// Forward executes a client op on this node, which must be an eligible
	// owner of the key's partition (applier-eligible for writes, read-set
	// member for reads). It never re-forwards.
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	// ApplyDelta merges a replicated delta into local state. Accepted while
	// active or bootstrapping.
	ApplyDelta(ctx context.Context, in *ApplyDeltaRequest, opts ...grpc.CallOption) (*ApplyDeltaResponse, error)
	// MerkleRoot returns the partition's anti-entropy tree root.
	MerkleRoot(ctx context.Context, in *MerkleRootRequest, opts ...grpc.CallOption) (*MerkleRootResponse, error)
	// MerkleLeaves returns the partition's full leaf vector (only fetched
	// when roots differ).
	MerkleLeaves(ctx context.Context, in *MerkleLeavesRequest, opts ...grpc.CallOption) (*MerkleLeavesResponse, error)
	// SyncBucket streams the full documents of one merkle bucket.
	SyncBucket(ctx context.Context, in *SyncBucketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncDoc], error)
	// Snapshot streams every document of a partition from a consistent
	// storage snapshot (bootstrap transfer; overlapping live deltas are
	// handled by merge).
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncDoc], error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, Node_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ApplyDelta(ctx context.Context, in *ApplyDeltaRequest, opts ...grpc.CallOption) (*ApplyDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDeltaResponse)
	err := c.cc.Invoke(ctx, Node_ApplyDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) MerkleRoot(ctx context.Context, in *MerkleRootRequest, opts ...grpc.CallOption) (*MerkleRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleRootResponse)
	err := c.cc.Invoke(ctx, Node_MerkleRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) MerkleLeaves(ctx context.Context, in *MerkleLeavesRequest, opts ...grpc.CallOption) (*MerkleLeavesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleLeavesResponse)
	err := c.cc.Invoke(ctx, Node_MerkleLeaves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SyncBucket(ctx context.Context, in *SyncBucketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncDoc], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[0], Node_SyncBucket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncBucketRequest, SyncDoc]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_SyncBucketClient = grpc.ServerStreamingClient[SyncDoc]

func (c *nodeClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncDoc], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[1], Node_Snapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SyncDoc]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_SnapshotClient = grpc.ServerStreamingClient[SyncDoc]

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
//
// Node is the node-facing service: request forwarding, delta replication,
// anti-entropy, and partition transfer streams.
type NodeServer interface {
	// Forward executes a client op on this node, which must be an eligible
	// owner of the key's partition (applier-eligible for writes, read-set
	// member for reads). It never re-forwards.
	Forward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	// ApplyDelta merges a replicated delta into local state. Accepted while
	// active or bootstrapping.
	ApplyDelta(context.Context, *ApplyDeltaRequest) (*ApplyDeltaResponse, error)
	// MerkleRoot returns the partition's anti-entropy tree root.
	MerkleRoot(context.Context, *MerkleRootRequest) (*MerkleRootResponse, error)
	// MerkleLeaves returns the partition's full leaf vector (only fetched
	// when roots differ).
	MerkleLeaves(context.Context, *MerkleLeavesRequest) (*MerkleLeavesResponse, error)
	// SyncBucket streams the full documents of one merkle bucket.
	SyncBucket(*SyncBucketRequest, grpc.ServerStreamingServer[SyncDoc]) error
	// Snapshot streams every document of a partition from a consistent
	// storage snapshot (bootstrap transfer; overlapping live deltas are
	// handled by merge).
	Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[SyncDoc]) error
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Forward(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedNodeServer) ApplyDelta(context.Context, *ApplyDeltaRequest) (*ApplyDeltaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyDelta not implemented")
}
func (UnimplementedNodeServer) MerkleRoot(context.Context, *MerkleRootRequest) (*MerkleRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerkleRoot not implemented")
}
func (UnimplementedNodeServer) MerkleLeaves(context.Context, *MerkleLeavesRequest) (*MerkleLeavesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerkleLeaves not implemented")
}
func (UnimplementedNodeServer) SyncBucket(*SyncBucketRequest, grpc.ServerStreamingServer[SyncDoc]) error {
	return status.Error(codes.Unimplemented, "method SyncBucket not implemented")
}
func (UnimplementedNodeServer) Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[SyncDoc]) error {
	return status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ApplyDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ApplyDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_ApplyDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ApplyDelta(ctx, req.(*ApplyDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_MerkleRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).MerkleRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_MerkleRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).MerkleRoot(ctx, req.(*MerkleRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_MerkleLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).MerkleLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_MerkleLeaves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).MerkleLeaves(ctx, req.(*MerkleLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SyncBucket_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncBucketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServer).SyncBucket(m, &grpc.GenericServerStream[SyncBucketRequest, SyncDoc]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_SyncBucketServer = grpc.ServerStreamingServer[SyncDoc]

func _Node_Snapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServer).Snapshot(m, &grpc.GenericServerStream[SnapshotRequest, SyncDoc]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_SnapshotServer = grpc.ServerStreamingServer[SyncDoc]

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "convergekv.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _Node_Forward_Handler,
		},
		{
			MethodName: "ApplyDelta",
			Handler:    _Node_ApplyDelta_Handler,
		},
		{
			MethodName: "MerkleRoot",
			Handler:    _Node_MerkleRoot_Handler,
		},
		{
			MethodName: "MerkleLeaves",
			Handler:    _Node_MerkleLeaves_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncBucket",
			Handler:       _Node_SyncBucket_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Snapshot",
			Handler:       _Node_Snapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}
