// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type MerkleRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootRequest) Reset() {
	*x = MerkleRootRequest{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootRequest) ProtoMessage() {}

func (x *MerkleRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootRequest.ProtoReflect.Descriptor instead.
func (*MerkleRootRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *MerkleRootRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type MerkleRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          []byte                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootResponse) Reset() {
	*x = MerkleRootResponse{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootResponse) ProtoMessage() {}

func (x *MerkleRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootResponse.ProtoReflect.Descriptor instead.
func (*MerkleRootResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *MerkleRootResponse) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

type MerkleLeavesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleLeavesRequest) Reset() {
	*x = MerkleLeavesRequest{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleLeavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLeavesRequest) ProtoMessage() {}

func (x *MerkleLeavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLeavesRequest.ProtoReflect.Descriptor instead.
func (*MerkleLeavesRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *MerkleLeavesRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type MerkleLeavesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Buckets × 32 bytes, concatenated in bucket order.
	Leaves        []byte `protobuf:"bytes,1,opt,name=leaves,proto3" json:"leaves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleLeavesResponse) Reset() {
	*x = MerkleLeavesResponse{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleLeavesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLeavesResponse) ProtoMessage() {}

func (x *MerkleLeavesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLeavesResponse.ProtoReflect.Descriptor instead.
func (*MerkleLeavesResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *MerkleLeavesResponse) GetLeaves() []byte {
	if x != nil {
		return x.Leaves
	}
	return nil
}

type SyncBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Bucket        uint32                 `protobuf:"varint,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBucketRequest) Reset() {
	*x = SyncBucketRequest{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBucketRequest) ProtoMessage() {}

func (x *SyncBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBucketRequest.ProtoReflect.Descriptor instead.
func (*SyncBucketRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *SyncBucketRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *SyncBucketRequest) GetBucket() uint32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

type SyncDoc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Canonical encoding of the full document.
	Document      []byte `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDoc) Reset() {
	*x = SyncDoc{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDoc) ProtoMessage() {}

func (x *SyncDoc) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDoc.ProtoReflect.Descriptor instead.
func (*SyncDoc) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *SyncDoc) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SyncDoc) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

type ForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*ForwardRequest_Put
	//	*ForwardRequest_Delete
	//	*ForwardRequest_Get
	//	*ForwardRequest_Patch
	Op            isForwardRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForwardRequest) GetOp() isForwardRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *ForwardRequest) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *ForwardRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *ForwardRequest) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *ForwardRequest) GetPatch() *PatchRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Patch); ok {
			return x.Patch
		}
	}
	return nil
}

type isForwardRequest_Op interface {
	isForwardRequest_Op()
}

type ForwardRequest_Put struct {
	Put *PutRequest `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type ForwardRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type ForwardRequest_Get struct {
	Get *GetRequest `protobuf:"bytes,4,opt,name=get,proto3,oneof"`
}

type ForwardRequest_Patch struct {
	Patch *PatchRequest `protobuf:"bytes,5,opt,name=patch,proto3,oneof"`
}

func (*ForwardRequest_Put) isForwardRequest_Op() {}

func (*ForwardRequest_Delete) isForwardRequest_Op() {}

func (*ForwardRequest_Get) isForwardRequest_Op() {}

func (*ForwardRequest_Patch) isForwardRequest_Op() {}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Get           *GetResponse           `protobuf:"bytes,1,opt,name=get,proto3" json:"get,omitempty"` // set for get ops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *ForwardResponse) GetGet() *GetResponse {
	if x != nil {
		return x.Get
	}
	return nil
}

type ApplyDeltaRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Partition uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Key       []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Canonical encoding of the delta document.
	Delta         []byte `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDeltaRequest) Reset() {
	*x = ApplyDeltaRequest{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDeltaRequest) ProtoMessage() {}

func (x *ApplyDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDeltaRequest.ProtoReflect.Descriptor instead.
func (*ApplyDeltaRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyDeltaRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ApplyDeltaRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ApplyDeltaRequest) GetDelta() []byte {
	if x != nil {
		return x.Delta
	}
	return nil
}

type ApplyDeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDeltaResponse) Reset() {
	*x = ApplyDeltaResponse{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDeltaResponse) ProtoMessage() {}

func (x *ApplyDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDeltaResponse.ProtoReflect.Descriptor instead.
func (*ApplyDeltaResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\n" +
	"convergekv\x1a\bkv.proto\"/\n" +
	"\x0fSnapshotRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\"1\n" +
	"\x11MerkleRootRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\"(\n" +
	"\x12MerkleRootResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\fR\x04root\"3\n" +
	"\x13MerkleLeavesRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\".\n" +
	"\x14MerkleLeavesResponse\x12\x16\n" +
	"\x06leaves\x18\x01 \x01(\fR\x06leaves\"I\n" +
	"\x11SyncBucketRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\rR\x06bucket\"7\n" +
	"\aSyncDoc\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\fR\bdocument\"\xe7\x01\n" +
	"\x0eForwardRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x03put\x18\x02 \x01(\v2\x16.convergekv.PutRequestH\x00R\x03put\x123\n" +
	"\x06delete\x18\x03 \x01(\v2\x19.convergekv.DeleteRequestH\x00R\x06delete\x12*\n" +
	"\x03get\x18\x04 \x01(\v2\x16.convergekv.GetRequestH\x00R\x03get\x120\n" +
	"\x05patch\x18\x05 \x01(\v2\x18.convergekv.PatchRequestH\x00R\x05patchB\x04\n" +
	"\x02op\"<\n" +
	"\x0fForwardResponse\x12)\n" +
	"\x03get\x18\x01 \x01(\v2\x17.convergekv.GetResponseR\x03get\"Y\n" +
	"\x11ApplyDeltaRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\fR\x05delta\"\x14\n" +
	"\x12ApplyDeltaResponse2\xbb\x03\n" +
	"\x04Node\x12B\n" +
	"\aForward\x12\x1a.convergekv.ForwardRequest\x1a\x1b.convergekv.ForwardResponse\x12K\n" +
	"\n" +
	"ApplyDelta\x12\x1d.convergekv.ApplyDeltaRequest\x1a\x1e.convergekv.ApplyDeltaResponse\x12K\n" +
	"\n" +
	"MerkleRoot\x12\x1d.convergekv.MerkleRootRequest\x1a\x1e.convergekv.MerkleRootResponse\x12Q\n" +
	"\fMerkleLeaves\x12\x1f.convergekv.MerkleLeavesRequest\x1a .convergekv.MerkleLeavesResponse\x12B\n" +
	"\n" +
	"SyncBucket\x12\x1d.convergekv.SyncBucketRequest\x1a\x13.convergekv.SyncDoc0\x01\x12>\n" +
	"\bSnapshot\x12\x1b.convergekv.SnapshotRequest\x1a\x13.convergekv.SyncDoc0\x01B0Z.github.com/janthoXO/convergeKV/pkg/proto;protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_node_proto_goTypes = []any{
	(*SnapshotRequest)(nil),      // 0: convergekv.SnapshotRequest
	(*MerkleRootRequest)(nil),    // 1: convergekv.MerkleRootRequest
	(*MerkleRootResponse)(nil),   // 2: convergekv.MerkleRootResponse
	(*MerkleLeavesRequest)(nil),  // 3: convergekv.MerkleLeavesRequest
	(*MerkleLeavesResponse)(nil), // 4: convergekv.MerkleLeavesResponse
	(*SyncBucketRequest)(nil),    // 5: convergekv.SyncBucketRequest
	(*SyncDoc)(nil),              // 6: convergekv.SyncDoc
	(*ForwardRequest)(nil),       // 7: convergekv.ForwardRequest
	(*ForwardResponse)(nil),      // 8: convergekv.ForwardResponse
	(*ApplyDeltaRequest)(nil),    // 9: convergekv.ApplyDeltaRequest
	(*ApplyDeltaResponse)(nil),   // 10: convergekv.ApplyDeltaResponse
	(*PutRequest)(nil),           // 11: convergekv.PutRequest
	(*DeleteRequest)(nil),        // 12: convergekv.DeleteRequest
	(*GetRequest)(nil),           // 13: convergekv.GetRequest
	(*PatchRequest)(nil),         // 14: convergekv.PatchRequest
	(*GetResponse)(nil),          // 15: convergekv.GetResponse
}
var file_node_proto_depIdxs = []int32{
	11, // 0: convergekv.ForwardRequest.put:type_name -> convergekv.PutRequest
	12, // 1: convergekv.ForwardRequest.delete:type_name -> convergekv.DeleteRequest
	13, // 2: convergekv.ForwardRequest.get:type_name -> convergekv.GetRequest
	14, // 3: convergekv.ForwardRequest.patch:type_name -> convergekv.PatchRequest
	15, // 4: convergekv.ForwardResponse.get:type_name -> convergekv.GetResponse
	7,  // 5: convergekv.Node.Forward:input_type -> convergekv.ForwardRequest
	9,  // 6: convergekv.Node.ApplyDelta:input_type -> convergekv.ApplyDeltaRequest
	1,  // 7: convergekv.Node.MerkleRoot:input_type -> convergekv.MerkleRootRequest
	3,  // 8: convergekv.Node.MerkleLeaves:input_type -> convergekv.MerkleLeavesRequest
	5,  // 9: convergekv.Node.SyncBucket:input_type -> convergekv.SyncBucketRequest
	0,  // 10: convergekv.Node.Snapshot:input_type -> convergekv.SnapshotRequest
	8,  // 11: convergekv.Node.Forward:output_type -> convergekv.ForwardResponse
	10, // 12: convergekv.Node.ApplyDelta:output_type -> convergekv.ApplyDeltaResponse
	2,  // 13: convergekv.Node.MerkleRoot:output_type -> convergekv.MerkleRootResponse
	4,  // 14: convergekv.Node.MerkleLeaves:output_type -> convergekv.MerkleLeavesResponse
	6,  // 15: convergekv.Node.SyncBucket:output_type -> convergekv.SyncDoc
	6,  // 16: convergekv.Node.Snapshot:output_type -> convergekv.SyncDoc
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_kv_proto_init()
	file_node_proto_msgTypes[7].OneofWrappers = []any{
		(*ForwardRequest_Put)(nil),
		(*ForwardRequest_Delete)(nil),
		(*ForwardRequest_Get)(nil),
		(*ForwardRequest_Patch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
