// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*ForwardRequest_Put
	//	*ForwardRequest_Delete
	//	*ForwardRequest_Get
	Op            isForwardRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForwardRequest) GetOp() isForwardRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *ForwardRequest) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *ForwardRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *ForwardRequest) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Op.(*ForwardRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

type isForwardRequest_Op interface {
	isForwardRequest_Op()
}

type ForwardRequest_Put struct {
	Put *PutRequest `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type ForwardRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type ForwardRequest_Get struct {
	Get *GetRequest `protobuf:"bytes,4,opt,name=get,proto3,oneof"`
}

func (*ForwardRequest_Put) isForwardRequest_Op() {}

func (*ForwardRequest_Delete) isForwardRequest_Op() {}

func (*ForwardRequest_Get) isForwardRequest_Op() {}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Get           *GetResponse           `protobuf:"bytes,1,opt,name=get,proto3" json:"get,omitempty"` // set for get ops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardResponse) GetGet() *GetResponse {
	if x != nil {
		return x.Get
	}
	return nil
}

type ApplyDeltaRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Partition uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Key       []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Canonical encoding of the delta document.
	Delta         []byte `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDeltaRequest) Reset() {
	*x = ApplyDeltaRequest{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDeltaRequest) ProtoMessage() {}

func (x *ApplyDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDeltaRequest.ProtoReflect.Descriptor instead.
func (*ApplyDeltaRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyDeltaRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ApplyDeltaRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ApplyDeltaRequest) GetDelta() []byte {
	if x != nil {
		return x.Delta
	}
	return nil
}

type ApplyDeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDeltaResponse) Reset() {
	*x = ApplyDeltaResponse{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDeltaResponse) ProtoMessage() {}

func (x *ApplyDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDeltaResponse.ProtoReflect.Descriptor instead.
func (*ApplyDeltaResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\n" +
	"convergekv\x1a\bkv.proto\"\xb5\x01\n" +
	"\x0eForwardRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x03put\x18\x02 \x01(\v2\x16.convergekv.PutRequestH\x00R\x03put\x123\n" +
	"\x06delete\x18\x03 \x01(\v2\x19.convergekv.DeleteRequestH\x00R\x06delete\x12*\n" +
	"\x03get\x18\x04 \x01(\v2\x16.convergekv.GetRequestH\x00R\x03getB\x04\n" +
	"\x02op\"<\n" +
	"\x0fForwardResponse\x12)\n" +
	"\x03get\x18\x01 \x01(\v2\x17.convergekv.GetResponseR\x03get\"Y\n" +
	"\x11ApplyDeltaRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\fR\x05delta\"\x14\n" +
	"\x12ApplyDeltaResponse2\x97\x01\n" +
	"\x04Node\x12B\n" +
	"\aForward\x12\x1a.convergekv.ForwardRequest\x1a\x1b.convergekv.ForwardResponse\x12K\n" +
	"\n" +
	"ApplyDelta\x12\x1d.convergekv.ApplyDeltaRequest\x1a\x1e.convergekv.ApplyDeltaResponseB0Z.github.com/janthoXO/convergeKV/pkg/proto;protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_node_proto_goTypes = []any{
	(*ForwardRequest)(nil),     // 0: convergekv.ForwardRequest
	(*ForwardResponse)(nil),    // 1: convergekv.ForwardResponse
	(*ApplyDeltaRequest)(nil),  // 2: convergekv.ApplyDeltaRequest
	(*ApplyDeltaResponse)(nil), // 3: convergekv.ApplyDeltaResponse
	(*PutRequest)(nil),         // 4: convergekv.PutRequest
	(*DeleteRequest)(nil),      // 5: convergekv.DeleteRequest
	(*GetRequest)(nil),         // 6: convergekv.GetRequest
	(*GetResponse)(nil),        // 7: convergekv.GetResponse
}
var file_node_proto_depIdxs = []int32{
	4, // 0: convergekv.ForwardRequest.put:type_name -> convergekv.PutRequest
	5, // 1: convergekv.ForwardRequest.delete:type_name -> convergekv.DeleteRequest
	6, // 2: convergekv.ForwardRequest.get:type_name -> convergekv.GetRequest
	7, // 3: convergekv.ForwardResponse.get:type_name -> convergekv.GetResponse
	0, // 4: convergekv.Node.Forward:input_type -> convergekv.ForwardRequest
	2, // 5: convergekv.Node.ApplyDelta:input_type -> convergekv.ApplyDeltaRequest
	1, // 6: convergekv.Node.Forward:output_type -> convergekv.ForwardResponse
	3, // 7: convergekv.Node.ApplyDelta:output_type -> convergekv.ApplyDeltaResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_kv_proto_init()
	file_node_proto_msgTypes[0].OneofWrappers = []any{
		(*ForwardRequest_Put)(nil),
		(*ForwardRequest_Delete)(nil),
		(*ForwardRequest_Get)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
